name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - master

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git push https://zyy213366:$HF_TOKEN@huggingface.co/spaces/zyy213366/excel-analyse master --force
